/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import HELPER.Auth;
import HELPER.MsgBox;
import ThreadClock.Time;

/**
 *
 * @author Administrator
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        init();
//        setResizable(false);

    }

    void init() {
        setLocationRelativeTo(null);
        this.ThrTime();
        openChao();
        openDangNhap();

    }

    void openChao() {
        new ManHinhChao(this, true).setVisible(true);
    }

    void openDangNhap() {
        new DangNhapJDialog(this, true).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIntroduce = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnChuyenDe = new javax.swing.JButton();
        btnNguoiHoc = new javax.swing.JButton();
        btnKhoaHoc = new javax.swing.JButton();
        btnHocVien = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnTroGiup = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblIntroduce1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnu_DoiMatKhau = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        MenuQL = new javax.swing.JMenu();
        ItemChuyenDe = new javax.swing.JMenuItem();
        ItemKhoaHoc = new javax.swing.JMenuItem();
        ItemHocVien = new javax.swing.JMenuItem();
        ItemNguoiHoc = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnu_NhanVien = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnu_BangDiem = new javax.swing.JMenuItem();
        mnu_LuongNguoiHoc = new javax.swing.JMenuItem();
        mnu_DiemChuyenDe = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnu_DoanhThu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        lblIntroduce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/gioithieu.png"))); // NOI18N
        lblIntroduce.setText("Hệ thống quản lí đào tạo");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BackgroundPoly.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(142, 142, 142))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setBorder(null);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/Logout.png"))); // NOI18N
        jButton1.setText("Đăng xuất");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/Stop sign.png"))); // NOI18N
        jButton2.setText("Kết thúc");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator1);

        btnChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/contract.png"))); // NOI18N
        btnChuyenDe.setText("Chuyên đề");
        btnChuyenDe.setFocusable(false);
        btnChuyenDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyenDe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenDeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnChuyenDe);

        btnNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/users4.png"))); // NOI18N
        btnNguoiHoc.setText("Người học");
        btnNguoiHoc.setFocusable(false);
        btnNguoiHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNguoiHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguoiHocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNguoiHoc);

        btnKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/course.png"))); // NOI18N
        btnKhoaHoc.setText("Khóa học");
        btnKhoaHoc.setFocusable(false);
        btnKhoaHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhoaHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaHocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKhoaHoc);

        btnHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/Student.png"))); // NOI18N
        btnHocVien.setText("Học viên");
        btnHocVien.setFocusable(false);
        btnHocVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHocVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocVienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHocVien);
        jToolBar1.add(jSeparator2);

        btnTroGiup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/help.png"))); // NOI18N
        btnTroGiup.setText("Hướng dẫn");
        btnTroGiup.setFocusable(false);
        btnTroGiup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTroGiup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTroGiup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroGiupActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTroGiup);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/Alarm clock.png"))); // NOI18N

        lblTime.setText("08:08:00 AM");

        lblIntroduce1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/gioithieu.png"))); // NOI18N
        lblIntroduce1.setText("Hệ thống quản lí đào tạo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(lblIntroduce1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIntroduce1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/Home.png"))); // NOI18N
        jMenu1.setText("Hệ thống");

        mnu_DoiMatKhau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnu_DoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/Lock.png"))); // NOI18N
        mnu_DoiMatKhau.setText("Đổi mật khẩu");
        mnu_DoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_DoiMatKhauActionPerformed(evt);
            }
        });
        jMenu1.add(mnu_DoiMatKhau);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/Logout.png"))); // NOI18N
        jMenuItem2.setText("Đăng xuất");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/exit-icon.png"))); // NOI18N
        jMenuItem3.setText("Kết thúc");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        MenuQL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/QuanLy.png"))); // NOI18N
        MenuQL.setText("Quản lý");

        ItemChuyenDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ItemChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/List.png"))); // NOI18N
        ItemChuyenDe.setText("Chuyên đề");
        ItemChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemChuyenDeActionPerformed(evt);
            }
        });
        MenuQL.add(ItemChuyenDe);

        ItemKhoaHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ItemKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/course.png"))); // NOI18N
        ItemKhoaHoc.setText("Khóa học");
        ItemKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemKhoaHocActionPerformed(evt);
            }
        });
        MenuQL.add(ItemKhoaHoc);

        ItemHocVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ItemHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/Student.png"))); // NOI18N
        ItemHocVien.setText("Học viên");
        ItemHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemHocVienActionPerformed(evt);
            }
        });
        MenuQL.add(ItemHocVien);

        ItemNguoiHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ItemNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/users4.png"))); // NOI18N
        ItemNguoiHoc.setText("Người học");
        ItemNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemNguoiHocActionPerformed(evt);
            }
        });
        MenuQL.add(ItemNguoiHoc);
        MenuQL.add(jSeparator4);

        mnu_NhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnu_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/People.png"))); // NOI18N
        mnu_NhanVien.setText("Nhân Viên");
        mnu_NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_NhanVienActionPerformed(evt);
            }
        });
        MenuQL.add(mnu_NhanVien);

        jMenuBar1.add(MenuQL);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/sort_ascending2.png"))); // NOI18N
        jMenu3.setText("Thống kê");

        mnu_BangDiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnu_BangDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/tablediem.png"))); // NOI18N
        mnu_BangDiem.setText("Bảng điểm");
        mnu_BangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_BangDiemActionPerformed(evt);
            }
        });
        jMenu3.add(mnu_BangDiem);

        mnu_LuongNguoiHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnu_LuongNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/users4.png"))); // NOI18N
        mnu_LuongNguoiHoc.setText("Lượng người học");
        mnu_LuongNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_LuongNguoiHocActionPerformed(evt);
            }
        });
        jMenu3.add(mnu_LuongNguoiHoc);

        mnu_DiemChuyenDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnu_DiemChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/diemchuyende.png"))); // NOI18N
        mnu_DiemChuyenDe.setText("Điểm chuyên đề");
        mnu_DiemChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_DiemChuyenDeActionPerformed(evt);
            }
        });
        jMenu3.add(mnu_DiemChuyenDe);
        jMenu3.add(jSeparator3);

        mnu_DoanhThu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnu_DoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/money_coins2.png"))); // NOI18N
        mnu_DoanhThu.setText("Doanh Thu");
        mnu_DoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_DoanhThuActionPerformed(evt);
            }
        });
        jMenu3.add(mnu_DoanhThu);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/help.png"))); // NOI18N
        jMenu4.setText("Trợ giúp");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/gioithieu.png"))); // NOI18N
        jMenuItem1.setText("Giới thiệu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/help.png"))); // NOI18N
        jMenuItem8.setText("Hướng dẫn sử dụng");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnu_NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_NhanVienActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            NhanVienInternalFrame a = new NhanVienInternalFrame();
            jDesktopPane1.add(a);
            a.setLocation((jDesktopPane1.getWidth() - a.getWidth()) / 2, (jDesktopPane1.getHeight() - a.getHeight()) / 2);
            a.setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }//GEN-LAST:event_mnu_NhanVienActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mnu_DoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_DoiMatKhauActionPerformed
        // TODO add your handling code here:

        if (Auth.isLogin()) {
            DoiMatKhauInternalFrame doi = new DoiMatKhauInternalFrame();
            jDesktopPane1.add(doi);
            doi.setLocation((jDesktopPane1.getWidth() - doi.getWidth()) / 2, (jDesktopPane1.getHeight() - doi.getHeight()) / 2);
            doi.setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }//GEN-LAST:event_mnu_DoiMatKhauActionPerformed

    private void btnChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenDeActionPerformed
        // TODO add your handling code here:

        if (Auth.isLogin()) {
            ChuyenDeInternalFrame doi = new ChuyenDeInternalFrame();
            jDesktopPane1.add(doi);
            doi.setLocation((jDesktopPane1.getWidth() - doi.getWidth()) / 2, (jDesktopPane1.getHeight() - doi.getHeight()) / 2);
            doi.setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }//GEN-LAST:event_btnChuyenDeActionPerformed

    private void btnNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguoiHocActionPerformed
        if (Auth.isLogin()) {
            QLNguoiHoc nh = new QLNguoiHoc();
            jDesktopPane1.add(nh);
            nh.setLocation((jDesktopPane1.getWidth() - nh.getWidth()) / 2, (jDesktopPane1.getHeight() - nh.getHeight()) / 2);
            nh.setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }//GEN-LAST:event_btnNguoiHocActionPerformed

    private void btnHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocVienActionPerformed
        if (Auth.isLogin()) {
            QLHocVien hv = new QLHocVien();
            jDesktopPane1.add(hv);
            hv.setLocation((jDesktopPane1.getWidth() - hv.getWidth()) / 2, (jDesktopPane1.getHeight() - hv.getHeight()) / 2);
            hv.setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }//GEN-LAST:event_btnHocVienActionPerformed

    private void btnTroGiupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroGiupActionPerformed
        if (Auth.isLogin()) {
            TroGiup tr = new TroGiup();
            jDesktopPane1.add(tr);
            tr.setLocation((jDesktopPane1.getWidth() - tr.getWidth()) / 2, (jDesktopPane1.getHeight() - tr.getHeight()) / 2);
            tr.setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }//GEN-LAST:event_btnTroGiupActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        if (Auth.isLogin()) {
            TroGiup tr = new TroGiup();
            jDesktopPane1.add(tr);
            tr.setLocation((jDesktopPane1.getWidth() - tr.getWidth()) / 2, (jDesktopPane1.getHeight() - tr.getHeight()) / 2);
            tr.setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void btnKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaHocActionPerformed
        if (Auth.isLogin()) {
            QLKhoaHoc kh = new QLKhoaHoc();
            jDesktopPane1.add(kh);
            kh.setLocation((jDesktopPane1.getWidth() - kh.getWidth()) / 2, (jDesktopPane1.getHeight() - kh.getHeight()) / 2);
            kh.setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }//GEN-LAST:event_btnKhoaHocActionPerformed

    private void ItemNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemNguoiHocActionPerformed
        if (Auth.isLogin()) {
            QLNguoiHoc nh = new QLNguoiHoc();
            jDesktopPane1.add(nh);
            nh.setLocation((jDesktopPane1.getWidth() - nh.getWidth()) / 2, (jDesktopPane1.getHeight() - nh.getHeight()) / 2);
            nh.setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }//GEN-LAST:event_ItemNguoiHocActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (Auth.isLogin()) {
            GioiThieu gt = new GioiThieu();
            jDesktopPane1.add(gt);
            gt.setLocation((jDesktopPane1.getWidth() - gt.getWidth()) / 2, (jDesktopPane1.getHeight() - gt.getHeight()) / 2);
            gt.setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ItemKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemKhoaHocActionPerformed
        btnKhoaHocActionPerformed(evt);
    }//GEN-LAST:event_ItemKhoaHocActionPerformed

    private void ItemHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemHocVienActionPerformed
        btnHocVienActionPerformed(evt);
    }//GEN-LAST:event_ItemHocVienActionPerformed

    private void ItemChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemChuyenDeActionPerformed
        btnChuyenDeActionPerformed(evt);
    }//GEN-LAST:event_ItemChuyenDeActionPerformed

    public void openThongKe(int index) {
        TongHopThongKeInternalFrame a = new TongHopThongKeInternalFrame(index);
        jDesktopPane1.add(a);
        a.setLocation((jDesktopPane1.getWidth() - a.getWidth()) / 2, (jDesktopPane1.getHeight() - a.getHeight()) / 2);
        a.setVisible(true);
    }
    private void mnu_BangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_BangDiemActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            openThongKe(0);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }//GEN-LAST:event_mnu_BangDiemActionPerformed

    private void mnu_LuongNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_LuongNguoiHocActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            openThongKe(1);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }//GEN-LAST:event_mnu_LuongNguoiHocActionPerformed

    private void mnu_DiemChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_DiemChuyenDeActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            openThongKe(2);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }//GEN-LAST:event_mnu_DiemChuyenDeActionPerformed

    private void mnu_DoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_DoanhThuActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            if (Auth.user.isVaiTro() == true) {
                openThongKe(3);
            } else {
                MsgBox.alert(this, "Bạn không được xem doanh thu");
            }
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }


    }//GEN-LAST:event_mnu_DoanhThuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Home main = new Home();
        main.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
        Home main = new Home();
        main.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    private void ThrTime() {
        Time time = new Time(lblTime);
        time.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemChuyenDe;
    private javax.swing.JMenuItem ItemHocVien;
    private javax.swing.JMenuItem ItemKhoaHoc;
    private javax.swing.JMenuItem ItemNguoiHoc;
    private javax.swing.JMenu MenuQL;
    private javax.swing.JButton btnChuyenDe;
    private javax.swing.JButton btnHocVien;
    private javax.swing.JButton btnKhoaHoc;
    private javax.swing.JButton btnNguoiHoc;
    private javax.swing.JButton btnTroGiup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblIntroduce;
    private javax.swing.JLabel lblIntroduce1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel logo;
    private javax.swing.JMenuItem mnu_BangDiem;
    private javax.swing.JMenuItem mnu_DiemChuyenDe;
    private javax.swing.JMenuItem mnu_DoanhThu;
    private javax.swing.JMenuItem mnu_DoiMatKhau;
    private javax.swing.JMenuItem mnu_LuongNguoiHoc;
    private javax.swing.JMenuItem mnu_NhanVien;
    // End of variables declaration//GEN-END:variables
}
