/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.KhoaHocDAO;
import DAO.chuyenDeDAO;
import HELPER.Auth;
import MODEL.ChuyenDe;
import MODEL.KhoaHoc;
import helper.dateHelper;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class QLKhoaHoc extends javax.swing.JInternalFrame {

    KhoaHocDAO khdao = new KhoaHocDAO();
    chuyenDeDAO cddao = new chuyenDeDAO();

    /**
     * Creates new form QLKhoaHoc
     */
    public QLKhoaHoc() {
        initComponents();
        this.init();
    }

    void init() {
        this.SetCombo();
        this.SetDate();
        this.SetEnable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tab = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtChuyende = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNgaKG = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtThoiLuong = new javax.swing.JTextField();
        txtHocPhi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        txtNgayTao = new javax.swing.JTextField();
        txtNguoiTao = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhoaHoc = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSerchDS = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboChuyenDe = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Quản lí khóa học");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/Add.png"))); // NOI18N
        btnThem.setText("Thêm ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/Update.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/New.png"))); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SVN-Androgyne", 0, 12)); // NOI18N
        jLabel3.setText("Chuyên Đề");

        txtChuyende.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("SVN-Androgyne", 0, 12)); // NOI18N
        jLabel4.setText("Khai Giảng");

        txtNgaKG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("SVN-Androgyne", 0, 12)); // NOI18N
        jLabel5.setText("Học Phí");

        jLabel6.setFont(new java.awt.Font("SVN-Androgyne", 0, 12)); // NOI18N
        jLabel6.setText("Thời lượng(giờ)");

        txtThoiLuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtHocPhi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("SVN-Androgyne", 0, 12)); // NOI18N
        jLabel8.setText("Ngày tạo");

        jLabel10.setFont(new java.awt.Font("SVN-Androgyne", 0, 12)); // NOI18N
        jLabel10.setText("Ghi chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane2.setViewportView(txtGhiChu);

        txtNgayTao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtNguoiTao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("SVN-Androgyne", 0, 12)); // NOI18N
        jLabel11.setText("Người tạo");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgaKG, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtThoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtChuyende, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNguoiTao, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChuyende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNguoiTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtThoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgaKG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXoa)
                        .addComponent(btnSua)
                        .addComponent(btnThem)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(389, 389, 389))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Tab.addTab("Cập nhật", jPanel3);

        tblKhoaHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã KH", "Thời lượng", "Học phí", "Khai giảng", "Ngày tạo"
            }
        ));
        tblKhoaHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhoaHocMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblKhoaHocMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhoaHoc);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("SVN-Androgyne", 0, 11)); // NOI18N
        jLabel9.setText("Nhập mã khóa học");

        btnSerchDS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/Search.png"))); // NOI18N
        btnSerchDS.setText("Tìm Kiếm");
        btnSerchDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerchDSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSerchDS)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSerchDS))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
        );

        Tab.addTab("Danh Sách", jPanel2);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("SVN-Androgyne", 0, 12)); // NOI18N
        jLabel2.setText("Chuyên Đề");

        cboChuyenDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboChuyenDeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Tab, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 13, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tab))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    public ChuyenDe ChuyenDeAction() {
        DefaultComboBoxModel mol = (DefaultComboBoxModel) cboChuyenDe.getModel();
        String tencd = String.valueOf(mol.getSelectedItem());
        String ma = LayMaCD(tencd);
        ChuyenDe cd = cddao.selectById(ma);
        this.FillTable();
        return cd;
    }
    private void cboChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboChuyenDeActionPerformed
        ChuyenDe cd = this.ChuyenDeAction();

        try {
            int hocphi = (int) cd.getHocPhi();
            txtChuyende.setText(cd.getTenCD());
            txtHocPhi.setText(String.valueOf(hocphi));
            txtThoiLuong.setText(String.valueOf(cd.getThoiLuong()));
            txtGhiChu.setText(cd.getTenCD());
            
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cboChuyenDeActionPerformed

    private void btnSerchDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerchDSActionPerformed
        String rgSo = "\\d+";
        if (txtSearch.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Phải nhập vào mã khóa học đề để tìm kiếm!", "", JOptionPane.ERROR_MESSAGE);
            txtSearch.requestFocus();
            return;
        } else if (txtSearch.getText().matches(rgSo) == false) {
            JOptionPane.showMessageDialog(this, "Mã khóa học là số nguyên");
            txtSearch.requestFocus();
            return;
        } else {
            int ma = Integer.valueOf(txtSearch.getText());
            TimKiemInDanhSach(ma);
        }
    }//GEN-LAST:event_btnSerchDSActionPerformed

    int row=-1;
    void setForm(KhoaHoc nv){
       txtChuyende.setText(nv.getMaCD());
       txtHocPhi.setText(nv.getHocPhi()+"");
       txtNgaKG.setText(dateHelper.toString(nv.getNgayKG() ));
      txtNgayTao.setText(dateHelper.toString(nv.getNgayTao()));
      txtNgayTao.setText(nv.getMaNV());
      txtThoiLuong.setText(nv.getThoiLuong()+"");
      txtGhiChu.setText(nv.getGhiChu());
    }
    void edit(){
        KhoaHocDAO dao=new KhoaHocDAO();
        String manv=(String)tblKhoaHoc.getValueAt(row, 0);
        KhoaHoc nv=dao.selectById(manv);
        setForm(nv);
        Tab.setSelectedIndex(0);
        
    }
    private void tblKhoaHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhoaHocMouseClicked
       this.ClickTable();
       btnXoa.setEnabled(true);
    }//GEN-LAST:event_tblKhoaHocMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        this.ClearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.Them();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        this.Xoa();
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        this.Sua();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblKhoaHocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhoaHocMousePressed
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            row=tblKhoaHoc.getSelectedRow();
            edit();
//            btnSua.setEnabled(true);
//            btnThem.setEnabled(false);
        }
        
    }//GEN-LAST:event_tblKhoaHocMousePressed

    public void SetCombo() {
        DefaultComboBoxModel mol = (DefaultComboBoxModel) cboChuyenDe.getModel();
        mol.removeAllElements();

        List<ChuyenDe> ls = cddao.selectAll();
        for (ChuyenDe cd : ls) {
            mol.addElement(cd.getTenCD());
        }
    }

    private void SetEnable() {
        Auth auth = new Auth();
        if (!auth.isManager()) {
            btnXoa.setEnabled(false);
        }

        txtNguoiTao.setText(String.valueOf(Auth.user.getMaNV()));

        txtChuyende.setEnabled(false);
        txtNguoiTao.setEnabled(false);
        btnSua.setEnabled(false);
        txtHocPhi.setEnabled(false);
        txtThoiLuong.setEnabled(false);
        txtNgayTao.setEnabled(false);
    }

    private void FillTable() {
        DefaultTableModel mol = (DefaultTableModel) tblKhoaHoc.getModel();

        mol.setRowCount(0);
        try {
            String ten = String.valueOf(cboChuyenDe.getSelectedItem());
            String ma = LayMaCD(ten);
            List<KhoaHoc> list = khdao.selectByChuyenDe(ma);

            for (KhoaHoc kh : list) {
                mol.addRow(new Object[]{kh.getMaKH(), kh.getThoiLuong(), kh.getHocPhi(), dateHelper.toString(kh.getNgayKG()),  dateHelper.toString(kh.getNgayTao())});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void TimKiemInDanhSach(int ma) {
        KhoaHoc kh = khdao.selectById(ma);
        String ten = String.valueOf(cboChuyenDe.getSelectedItem());
        String macd = LayMaCD(ten);
        List<KhoaHoc> list = khdao.selectByChuyenDe(macd);
        int index = -1;
        if (kh == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy.");
            txtSearch.requestFocus();
            return;
        } else {
            for (int i = 0; i < list.size(); i++) {
                if (kh.getMaKH() == list.get(i).getMaKH()) {
                    index = i;
                    break;
                } else {
                    index = -1;
                }
            }
        }
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Khóa học này không có trong chuyên đề " + ten);
            txtSearch.requestFocus();
            return;
        } else {
            this.tblKhoaHoc.setRowSelectionInterval(index, index);
        }
    }

    private void SetForm(KhoaHoc kh) {
        List<ChuyenDe> listCD = cddao.selectAll();
        String tencd = null;
        for (ChuyenDe cd : listCD) {
            if (kh.getMaCD().equals(cd.getMaCD())) {
                tencd = cd.getTenCD();
            }
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        txtChuyende.setText(tencd);
        txtGhiChu.setText(kh.getGhiChu());
        txtHocPhi.setText(String.valueOf(kh.getHocPhi()));
        txtNgaKG.setText(String.valueOf(kh.getNgayKG()));
        String ngaytao = sdf.format(kh.getNgayTao());
        txtNgayTao.setText(ngaytao);
        txtThoiLuong.setText(String.valueOf(kh.getThoiLuong()));
        txtNguoiTao.setText(kh.getMaNV());

    }

    private int ClickTable() {
        String ten = (String) cboChuyenDe.getSelectedItem();
        int index = tblKhoaHoc.getSelectedRow();
        List<KhoaHoc> listKH = khdao.selectByChuyenDe(this.LayMaCD(ten));
        KhoaHoc kh = listKH.get(index);
        SetForm(kh);
        Tab.setSelectedIndex(0);
        btnSua.setEnabled(true);
        btnThem.setEnabled(false);
        return 1;
    }

    public void ClearForm() {
        txtGhiChu.setText("");
        txtNgaKG.setText("");
        btnThem.setEnabled(true);
        btnSua.setEnabled(false);
    }

    public KhoaHoc GetForm() {
        KhoaHoc kh = new KhoaHoc();
        List<KhoaHoc> ls = khdao.selectAll();
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String ngaytao = txtNgayTao.getText();
            String ngayKG = txtNgaKG.getText();
            String ten = (String) cboChuyenDe.getSelectedItem();
            String ma = LayMaCD(ten);
            kh.setMaKH(ls.size() + 1);
            kh.setMaCD(ma);
            kh.setMaNV(txtNguoiTao.getText());
            kh.setHocPhi(Integer.valueOf(txtHocPhi.getText()));
            kh.setThoiLuong(Integer.valueOf(txtThoiLuong.getText()));
            kh.setNgayKG(sdf.parse(ngayKG));
            kh.setNgayTao(sdf.parse(ngaytao));
            kh.setGhiChu(txtGhiChu.getText());
            return kh;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public KhoaHoc GetFormSua(KhoaHoc a) {
        KhoaHoc kh = new KhoaHoc();
        List<KhoaHoc> ls = khdao.selectAll();
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String ngaytao = txtNgayTao.getText();
            String ngayKG = txtNgaKG.getText();
            String ten = (String) cboChuyenDe.getSelectedItem();
            String ma = LayMaCD(ten);
            kh.setMaKH(a.getMaKH());
            kh.setMaCD(ma);
            kh.setMaNV(txtNguoiTao.getText());
            kh.setHocPhi(Integer.valueOf(txtHocPhi.getText()));
            kh.setThoiLuong(Integer.valueOf(txtThoiLuong.getText()));
            kh.setNgayKG(sdf.parse(ngayKG));
            kh.setNgayTao(sdf.parse(ngaytao));
            kh.setGhiChu(txtGhiChu.getText());
            return kh;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public void SetDate() {
        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String date = sdf.format(now);
        txtNgayTao.setText(date);
    }

    private void Them() {
        try {
            String rgdate = "(?:(?:31(\\/|-|\\.)(?:0?[13578]|1[02]))\\1|(?:(?:29|30)"
                    + "(\\/|-|\\.)(?:0?[13-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d"
                    + "{2})$|^(?:29(\\/|-|\\.)0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0"
                    + "[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])"
                    + "00))))$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$";
            if (txtNgaKG.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Nhập vào ngày khai giảng");
                txtNgaKG.requestFocus();
                return;
            } else if (txtNgaKG.getText().matches(rgdate) == false) {
                JOptionPane.showMessageDialog(this, "Không đúng định dạng.");
                txtNgaKG.requestFocus();
                return;
            } else {
                KhoaHoc kh = this.GetForm();
                if (khdao.Insert(kh) > 0) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    this.FillTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Kiểm tra lại thông tin");
                }

            }
        } catch (Exception e) {
        }
    }

    private void Sua() {
        try {
            String rgdate = "(?:(?:31(\\/|-|\\.)(?:0?[13578]|1[02]))\\1|(?:(?:29|30)"
                    + "(\\/|-|\\.)(?:0?[13-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d"
                    + "{2})$|^(?:29(\\/|-|\\.)0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0"
                    + "[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])"
                    + "00))))$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$";
            if (txtNgaKG.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Nhập vào ngày khai giảng");
                txtNgaKG.requestFocus();
                return;
            } else if (txtNgaKG.getText().matches(rgdate) == false) {
                JOptionPane.showMessageDialog(this, "Không đúng định dạng.");
                txtNgaKG.requestFocus();
                return;
            } else {
                String ten = (String) cboChuyenDe.getSelectedItem();
                int index = tblKhoaHoc.getSelectedRow();
                List<KhoaHoc> listKH = khdao.selectByChuyenDe(this.LayMaCD(ten));
                KhoaHoc a = listKH.get(index);
                KhoaHoc kh = this.GetFormSua(a);
                if (khdao.Update(kh) > 0) {
                    JOptionPane.showMessageDialog(this, "Sửa thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Kiểm tra lại thông tin");
                }

            }
        } catch (Exception e) {
        }
    }

    private void Xoa() {
      try {
            String ten = (String) cboChuyenDe.getSelectedItem();
            List<KhoaHoc> listKH = khdao.selectByChuyenDe(this.LayMaCD(ten));
            int index = tblKhoaHoc.getSelectedRow();
            KhoaHoc kh = listKH.get(index);
            Integer ma = kh.getMaKH();
            if (kh == null) {
                String mas = JOptionPane.showInputDialog(this, "Nhập mã khóa học", "Xóa khóa học", JOptionPane.YES_NO_OPTION);
                if (khdao.Delete(mas) > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công.");
                    FillTable();
                    ClearForm();
                    return;
                } else {
                    JOptionPane.showMessageDialog(this, "Không thể xóa!\nKhóa học này đang có người học", "", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                
                int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa khóa học này không", "Xóa khóa học", JOptionPane.YES_NO_OPTION);
                if (a == JOptionPane.YES_OPTION) {
                    if (khdao.Delete(ma) > 0) {
                        JOptionPane.showMessageDialog(this, "Xóa thành công.");
                        FillTable();
                        ClearForm();
                        return;
                    } else if (khdao.Delete(ma) == 0) {
                        JOptionPane.showMessageDialog(this, "Sai mã khóa học", "", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Không thể xóa!\nKhóa học này đang có người học", "", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
            btnXoa.setEnabled(false);
        } catch (Exception e) {
//            String mas = JOptionPane.showInputDialog(this, "Nhập mã khóa học", "Xóa khóa học", JOptionPane.YES_NO_OPTION);
//            if (khdao.Delete(mas) > 0) {
//                JOptionPane.showMessageDialog(this, "Xóa thành công.");
//                FillTable();
//                ClearForm();
//                return;
//            } else {
//                JOptionPane.showMessageDialog(this, "Không thể xóa!\nKhóa học này đang có người học", "", JOptionPane.ERROR_MESSAGE);
//                return;
//            }
            JOptionPane.showMessageDialog(this, "Phải chọn khóa học để xóa", "", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tab;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSerchDS;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboChuyenDe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblKhoaHoc;
    private javax.swing.JTextField txtChuyende;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtHocPhi;
    private javax.swing.JTextField txtNgaKG;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtNguoiTao;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtThoiLuong;
    // End of variables declaration//GEN-END:variables

    private String LayMaCD(String ten) {
        List<ChuyenDe> ls = cddao.selectAll();
        String ma = null;
        for (int i = 0; i < ls.size(); i++) {
            if (ten.equals(ls.get(i).getTenCD())) {
                ma = ls.get(i).getMaCD();
            }
        }
        return ma;
    }
}
